import { createSystem, defaultConfig, defineConfig } from '@chakra-ui/react'

const customConfig = defineConfig({
  theme: {
    tokens: {
      colors: {
        brand: {
          50: { value: '#EAF6F5' },
          100: { value: '#D3EDEA' },
          200: { value: '#A8DBD5' },
          300: { value: '#7CC9C0' },
          400: { value: '#54B3A9' },
          500: { value: '#2E9E96' },
          600: { value: '#278C85' },
          700: { value: '#1F6F69' },
          800: { value: '#17534F' },
          900: { value: '#0F3634' },
          950: { value: '#081B1A' },
        },
        indigo: {
          50: { value: '#F1EFFD' },
          100: { value: '#E4E1FB' },
          200: { value: '#C9C3F7' },
          300: { value: '#AEA5F3' },
          400: { value: '#8779EC' },
          500: { value: '#5B4FE8' },
          600: { value: '#4A3ED0' },
          700: { value: '#3A30A8' },
          800: { value: '#2A2380' },
          900: { value: '#1B1652' },
          950: { value: '#0D0B29' },
        },
      },

      fonts: {
        heading: { value: 'Inter Variable, Inter, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif' },
        body: { value: 'Inter Variable, Inter, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif' },
        mono: { value: 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace' },
      },

      fontSizes: {
        '2xs': { value: '0.625rem' },
        xs: { value: '0.75rem' },
        sm: { value: '0.875rem' },
        md: { value: '1rem' },
        lg: { value: '1.125rem' },
        xl: { value: '1.25rem' },
        '2xl': { value: '1.5rem' },
        '3xl': { value: '1.875rem' },
        '4xl': { value: '2.25rem' },
        '5xl': { value: '3rem' },
        '6xl': { value: '3.75rem' },
        '7xl': { value: '4.5rem' },
        '8xl': { value: '6rem' },
        '9xl': { value: '8rem' },
      },

      fontWeights: {
        thin: { value: '100' },
        extralight: { value: '200' },
        light: { value: '300' },
        normal: { value: '400' },
        medium: { value: '500' },
        semibold: { value: '600' },
        bold: { value: '700' },
        extrabold: { value: '800' },
        black: { value: '900' },
      },

      spacing: {
        0.5: { value: '0.125rem' },
        1: { value: '0.25rem' },
        1.5: { value: '0.375rem' },
        2: { value: '0.5rem' },
        2.5: { value: '0.625rem' },
        3: { value: '0.75rem' },
        3.5: { value: '0.875rem' },
        4: { value: '1rem' },
        4.5: { value: '1.125rem' },
        5: { value: '1.25rem' },
        6: { value: '1.5rem' },
        7: { value: '1.75rem' },
        8: { value: '2rem' },
        9: { value: '2.25rem' },
        10: { value: '2.5rem' },
        11: { value: '2.75rem' },
        12: { value: '3rem' },
        14: { value: '3.5rem' },
        16: { value: '4rem' },
        20: { value: '5rem' },
        24: { value: '6rem' },
        28: { value: '7rem' },
        32: { value: '8rem' },
        36: { value: '9rem' },
        40: { value: '10rem' },
        44: { value: '11rem' },
        48: { value: '12rem' },
        52: { value: '13rem' },
        56: { value: '14rem' },
        60: { value: '15rem' },
        64: { value: '16rem' },
        72: { value: '18rem' },
        80: { value: '20rem' },
        96: { value: '24rem' },
      },
    },

    semanticTokens: {
      colors: {
        brand: {
          contrast: { value: { _light: 'white', _dark: 'white' } },
          fg: { value: { _light: '{colors.brand.700}', _dark: '{colors.brand.300}' } },
          subtle: { value: { _light: '{colors.brand.100}', _dark: '{colors.brand.900}' } },
          muted: { value: { _light: '{colors.brand.200}', _dark: '{colors.brand.800}' } },
          emphasized: { value: { _light: '{colors.brand.300}', _dark: '{colors.brand.700}' } },
          solid: { value: { _light: '{colors.brand.600}', _dark: '{colors.brand.600}' } },
          focusRing: { value: { _light: '{colors.brand.500}', _dark: '{colors.brand.500}' } },
          border: { value: { _light: '{colors.brand.500}', _dark: '{colors.brand.400}' } },
        },
        indigo: {
          contrast: { value: { _light: 'white', _dark: 'white' } },
          fg: { value: { _light: '{colors.indigo.700}', _dark: '{colors.indigo.300}' } },
          subtle: { value: { _light: '{colors.indigo.100}', _dark: '{colors.indigo.900}' } },
          muted: { value: { _light: '{colors.indigo.200}', _dark: '{colors.indigo.800}' } },
          emphasized: { value: { _light: '{colors.indigo.300}', _dark: '{colors.indigo.700}' } },
          solid: { value: { _light: '{colors.indigo.600}', _dark: '{colors.indigo.600}' } },
          focusRing: { value: { _light: '{colors.indigo.500}', _dark: '{colors.indigo.500}' } },
          border: { value: { _light: '{colors.indigo.500}', _dark: '{colors.indigo.400}' } },
        },
      },
    },
  },
})

export const system = createSystem(defaultConfig, customConfig)
